### ISSUE TITLE
RAG0014: Inclusion of older converstation in Chatbot

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/RAG_chatbot_interface#11]
## Description 
Currently, our chatbot can answer questions based on user input. However, as users ask more questions, the chatbot does not take previous interactions into account. Adding this feature will provide users with a more realistic chatbot experience and enable the chatbot to give more specific answers tailored to users' needs.

## Expected Output
The chatbot should be able to remember information from previous interactions and provide responses based on that context.

## Reference
[routing techniques](https://towardsdatascience.com/routing-in-rag-driven-applications-a685460a7220
)
## Implementation Steps
- [x] Include Previous Question and Answer in Context
- [x] Respond to Normal Conversations (Routing)
- [x] evaluate the chatbot response
- [x] Show Token Usage
- [x] Show a message when token limit exceeds [here](https://github.com/OpenPecha/RAG_chatbot_interface/issues/11#issuecomment-2273045058)

**Comment by tenzin3** [comment]
## How to include older conversation


![Image](https://github.com/user-attachments/assets/775ce28c-0365-443c-be25-488d441587a7)

**Comment by tenzin3** [comment]
## Routing based on query:

![Image](https://github.com/user-attachments/assets/e4291035-f6b6-4540-98a1-3401881325a3)

### Prompt
```
assifies the query into one of the predefined categories based on its content.

        Categories:
            - Normal Conversation: Casual greetings not specific to Dalai Lama or Tibet.
            - Gibberish: Incoherent or nonsensical text.
            - Genuine Query: Any valid question that seeks information or clarification.
            - Inappropriate: Queries containing harmful, offensive, derogatory, sexual or otherwise inappropriate language. This includes queries with negative sentiment or illegal content.
            - Non-English: Queries not written in English.


        Returns:
            str: The exact category of the query from the list above. The category should be returned exactly as mentioned, without any additional characters or quotes.

    """
```

### Queries and their classification result

![Image](https://github.com/user-attachments/assets/57355f6c-705f-4b2c-bfbf-e0df85e23035)

**Comment by tenzin3** [comment]
## RAG Chat Responses

## Normal Conversation
![Image](https://github.com/user-attachments/assets/e7485404-720d-4de0-9207-6723262c5247)

## Inappropriate
![Image](https://github.com/user-attachments/assets/15e06706-e646-4763-b6bc-255bb5203391)

## Non English
![Image](https://github.com/user-attachments/assets/39e3728f-dc17-40a0-9ad3-0b4d4bbf63a8)

## Giberish
![Image](https://github.com/user-attachments/assets/31b13ff3-2335-4bb2-875e-5236c2c8a070)

## Genuine Question
![Image](https://github.com/user-attachments/assets/97e292bc-5b4a-44a7-a780-057589bc09f7)

**Comment by tenzin3** [comment]
## Progress Bar
![Image](https://github.com/user-attachments/assets/484c2fc6-da88-44fd-96e6-e8f144397cae)

**Comment by tenzin3** [comment]
## Snippet picture when token limit reaches

![Image](https://github.com/user-attachments/assets/6a17a018-5cf7-413e-ad19-2ea317237727)
