### ISSUE TITLE
RAG0013: Modify/Add  Prompt for structural context retrieval (2)

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/RAG_chatbot_interface#8]
##  Description
Currently the language model that we are using phi3-mini-128k, and we are giving question, a predefined prompt with context for answer generation. And previously we were unsuccessful in defining a prompt that ables the language model to successfully return not only the answers but the exact snippets of the context it used for the answer generation.Refer [here](https://github.com/OpenPecha/rag_prep_tool/issues/9#issue-2332554246)

## Expected ouput
A defined prompt or prompts that enable to get the answer and the snippets of the contexts it used for answer generation.

## Implementation Steps

- [x] context retrieval in one prompt request
- [x] log the question and response
- [ ] context retrieval in multiple prompt request
- [x] modify frontend to print snippets in reference
- [ ] retrieve confidence score from llm
- [ ] modify frontend to print confidence score
- [x] enable streaming ouput from llm response to frontend

## Import Notes

- context retrieval in multiple prompt request was not need since it was possible in one request.
- confidence score has not been shown based on following reason
        1.   if it is getting proper answer from the context, it is only giving high percentage(mostly 100) and least i found is 95.
        2.   if it doesnt not have the answer, it doenst make sense to show a confidence score or references. right after printing "I don't have 
               enough data to provide an answer"
        (prompt and outputs are still shown in below comments)

**Comment by tenzin3** [comment]
## Successfully able to retrieve snippets from the context

![Image](https://github.com/OpenPecha/RAG_chatbot_interface/assets/52460417/b0e7f441-77e5-496f-81fe-11eecc9fb908)

## Given prompt
```

template = f"""
        You are his holiness the 14th Dalai Lama.
        
        Strictly follow these guidelines when answering the questions:
        
        - Answer the question based on the given context (some of which might be irrelevant).
        - Provide a short, informative, and pleasant response.
        - Use plain and respectful language.
        - If there is not enough information in the context to answer the question, respond with "I don't have enough data to provide an answer."

        Question: {question}
        {context}
        
        Your task is divided into two parts:
        
        1. **Get the Answer:**
        - Provide a concise and precise answer to the user's question based on the given context.
        - If you do not have enough data to provide an answer, respond with "I don't have enough data to provide an answer."
        
        2. **Find the Source Snippets:**
        - Extract and provide all relevant snippets from the contexts that directly support your answer.
        - Ensure each snippet retains the exact wording and spelling from the context.
        - Cite the source of each snippet (e.g., book title, page number, chapter) in italic.
        - Snippet from same source be shown together.
        - Separate each snippet and its source with a new line.
        - If you do not have a proper answer from the context, do not include references.

        Structure your response as follows:
        
        your_answer
        
        __References__
        1._source_:snippet_1   

        2._source_:snippet_2   
        
        ...
        """
```

#### Important Note
No parsing is done from chatgpt response, style for references is also specified in prompt such that response from the chatgpt is directly shown in markdown text through the streamlit(front-end)

**Comment by tenzin3** [comment]
####  Experimented with 100 questions all giving proper answer and references based on the prompt

**Comment by tenzin3** [comment]
## Ouput for chatgpt response with confidence score


![Image](https://github.com/OpenPecha/RAG_chatbot_interface/assets/52460417/8cb8b602-4c50-4ec6-992c-9481ccb2ab10)
![Image](https://github.com/OpenPecha/RAG_chatbot_interface/assets/52460417/11774002-3ebc-42eb-a434-f0405093bd7b)
![Image](https://github.com/OpenPecha/RAG_chatbot_interface/assets/52460417/c12b937c-4bcb-49bf-a93c-d71c7d6fc90c)
![Image](https://github.com/OpenPecha/RAG_chatbot_interface/assets/52460417/a93339a1-1d62-4b19-84ad-b53a58b9fac1)

## Prompt 

```
template = f"""
        You are his holiness the 14th Dalai Lama.
        
        Strictly follow these guidelines when answering the questions:
        
        - Answer the question based on the given context (some of which might be irrelevant).
        - Provide a short, informative, and pleasant response.
        - Use plain and respectful language.
        - If there is not enough information in the context to answer the question, only respond with 'I don't have enough data to provide an answer". Do not show confidence score and reference at all.

        
        Question: {question}
        {context}
        
        Your task is divided into two parts:
        
        1. **Get the Answer:**
        - Provide a concise and precise answer to the user's question based on the given context.
        
        2. **Confidence Score:**
        - Provide a confidence score (out of 100) for the accuracy of your answer based on the provided context.
        
        3. **Find the Source Snippets:**
        - Extract and provide all relevant snippets from the contexts that directly support your answer.
        - Ensure each snippet retains the exact wording and spelling from the context.
        - Cite the source of each snippet (e.g., book title, page number, chapter) in italic.
        - Snippet from same source be shown together.
        - Separate each snippet and its source with a new line.

        Structure your response as follows:
        
        your_answer

        __Confidence Score__: confidence_score%
        
        __References__
        1._source_:snippet_1   

        2._source_:snippet_2   
        
        ...
        """
```
